**Classification**

In [67]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


In [3]:
data=load_breast_cancer()
x=data.data
y=data.target

In [4]:
x=pd.DataFrame(x,columns=data.feature_names)
y=pd.Series(y)

In [5]:
print(type(x))
print(type(y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [6]:
x.isna().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
dtype: int64

In [7]:
y.isna().sum()

np.int64(0)

In [8]:
x.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


**No null values present is this dataset**

In [48]:
model_accuracy={}

**Created a dictionary to store the accuracy score of each model**

In [9]:
scaler=StandardScaler()

In [10]:
x=scaler.fit_transform(x)

**Using StandardScaler for scaling the values in the data and make it equal base to a certain value** 

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=42)

In [12]:
l_model=LogisticRegression()
l_model

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [13]:
l_model.fit(x_train,y_train)
l_model

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [49]:
l_y_pred=l_model.predict(x_test)

In [15]:
l_accuracyscore=accuracy_score(y_test,l_y_pred)
print(l_accuracyscore)

0.9736842105263158


In [50]:
model_accuracy["Logistic Regression"]=l_accuracyscore

In [16]:
print("Confusion Matrix \n",confusion_matrix(y_test,l_y_pred))

Confusion Matrix 
 [[41  2]
 [ 1 70]]


In [17]:
print("Classification Report \n",classification_report(y_test,l_y_pred))

Classification Report 
               precision    recall  f1-score   support

           0       0.98      0.95      0.96        43
           1       0.97      0.99      0.98        71

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



**Logistic regression is a classification algorithm that models the probability of a class by applying a sigmoid function to a linear combination of input features.**

**During training, it learns the optimal weights for each feature so that the predicted probabilities match the actual labels as closely as possible. It does this by fitting a linear equation to the data and then passing the result through a sigmoid function, which converts it into values between 0 and 1.**

**During testing, the model uses the learned parameters (weights) to compute the probability for new data points. Based on a threshold (commonly 0.5), it classifies the output into one of the target classes.**

In [18]:
dt=DecisionTreeClassifier(
    criterion='entropy',
    max_depth=4,
random_state=42)
dt

,criterion,'entropy'
,splitter,'best'
,max_depth,4
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [19]:
dt.fit(x_train,y_train)
dt

,criterion,'entropy'
,splitter,'best'
,max_depth,4
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [68]:
dt_y_pred=dt.predict(x_test)

In [21]:
dt_accuracyscore=accuracy_score(y_test,dt_y_pred)
print(dt_accuracyscore)

0.956140350877193


In [52]:
model_accuracy["Decision Tree Classifier"]=dt_accuracyscore

In [22]:
print("Confusion Matrix \n",confusion_matrix(y_test,dt_y_pred))

Confusion Matrix 
 [[39  4]
 [ 1 70]]


In [23]:
print("Classification Report \n",classification_report(y_test,dt_y_pred))

Classification Report 
               precision    recall  f1-score   support

           0       0.97      0.91      0.94        43
           1       0.95      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



**A Decision Tree Classifier builds a tree-like structure by repeatedly splitting the dataset based on feature values. At each node, it asks a question about a feature (e.g., "Is feature X ≤ value?") to divide the data into subsets.**

**The model selects the best feature for splitting by using measures like entropy or Gini impurity. These measures help determine how well a feature separates the data into different classes.**
  


In [24]:
Rf_model=RandomForestClassifier(n_estimators=100,random_state=42)
Rf_model

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [25]:
Rf_model.fit(x_train,y_train)
Rf_model

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [26]:
Rf_y_pred=Rf_model.predict(x_test)

In [27]:
Rf_accuracyscore=accuracy_score(y_test,Rf_y_pred)
print(Rf_accuracyscore)

0.9649122807017544


In [55]:
model_accuracy["Random Forest Classifier"]=Rf_accuracyscore

In [28]:
print("Confusion Matrix \n",confusion_matrix(y_test,Rf_y_pred))

Confusion Matrix 
 [[40  3]
 [ 1 70]]


In [29]:
print("Classification Report \n",classification_report(y_test,Rf_y_pred))

Classification Report 
               precision    recall  f1-score   support

           0       0.98      0.93      0.95        43
           1       0.96      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114



**Random Forest classifier is an ensemble method that builds multiple decision trees on different subsets of the data and combines their predictions (usually by majority voting) to improve accuracy and reduce overfitting.**

In [30]:
knn=KNeighborsClassifier(n_neighbors=5)
knn

,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [31]:
knn.fit(x_train,y_train)
knn

,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [32]:
knn_y_pred=knn.predict(x_test)

In [33]:
knn_accuracyscore=accuracy_score(y_test,knn_y_pred)
print(knn_accuracyscore)

0.9473684210526315


In [ ]:
model_accuracy["K Nearest Neigbhours"]=knn_accuracyscore

In [34]:
print("Confusion Matrix \n",confusion_matrix(y_test,knn_y_pred))

Confusion Matrix 
 [[40  3]
 [ 3 68]]


In [35]:
print("Classification Report \n",classification_report(y_test,knn_y_pred))

Classification Report 
               precision    recall  f1-score   support

           0       0.93      0.93      0.93        43
           1       0.96      0.96      0.96        71

    accuracy                           0.95       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114



**K-Nearest Neighbors (KNN) classifier classifies a data point based on the majority class among its k nearest neighbors in the feature space. It uses distance metrics (like Euclidean distance) to find the closest points.**

In [42]:
svm=SVC(kernel='rbf',C=1.0,gamma='scale')
svm

,C,1.0
,kernel,'rbf'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,False
,tol,0.001
,cache_size,200
,class_weight,None
,verbose,False


In [43]:
svm.fit(x_train,y_train)

,C,1.0
,kernel,'rbf'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,False
,tol,0.001
,cache_size,200
,class_weight,None
,verbose,False


In [44]:
svm_y_pred=svm.predict(x_test)
svm_y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [57]:
svm_accuracyscore=accuracy_score(y_test,svm_y_pred)
print(svm_accuracyscore)

0.9736842105263158


In [53]:
model_accuracy["SVM"]=svm_accuracyscore

In [58]:
print("Confusion Matrix \n",confusion_matrix(y_test,svm_y_pred))

Confusion Matrix 
 [[41  2]
 [ 1 70]]


In [59]:
print("Classification Report \n",classification_report(y_test,svm_y_pred))

Classification Report 
               precision    recall  f1-score   support

           0       0.98      0.95      0.96        43
           1       0.97      0.99      0.98        71

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



**Support Vector Machine (SVM) classifier finds the optimal boundary (hyperplane) that separates different classes with the maximum margin. It can use different kernels like linear or RBF to handle both linear and non-linear data.**

In [56]:
model_accuracy

{'Logistic Regression': 0.9736842105263158,
 'Decision Tree Classifier': 0.956140350877193,
 'SVM': 0.9736842105263158,
 'Random Forest Classifier': 0.9649122807017544}

**Accuracy of each model is stored in a dictionary along with the model name.**

In [66]:
maxaccuracy=max(model_accuracy,key=model_accuracy.get)
print(maxaccuracy)

Logistic Regression


**Maximum accuracy is for ***Logistic Regression*** model**

In [69]:
minaccuracy=min(model_accuracy,key=model_accuracy.get)
print(minaccuracy)

Decision Tree Classifier


**Minimum accuracy is for ***Decision Tree Classifier*** model**